#!/bin/bash
#dev_appserver.py --datastore_path=/var/leodev/db/soloteatro.db --use_sqlite --address=soloteatro . 
dev_appserver.py --datastore_path=/var/leodev/db/soloteatro.db --use_sqlite --address=localhost . 

